package:
  format-version: "1.0.0"
  name: "smartenergy_metersandmore"
  version: "v1.2.0"
  type: "api"
  status: "production"
  required: false

  dependencies:
    - name: "smartenergy"
      type: "package"
      version: "v1.5.0"
    - name: "crypto_v4"
      type: "package"
      version: "v4.0.0-E3"
    - name: "wolfssl"
      type: "package"
      version: "v5.7.0"
